name: CI/CD Pipeline
on:
  # Trigger the workflow only manually
  workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 15
        steps:
            - name: Checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  run_install: true
            - name: Cache pnpm modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install pnpm modules
              run: pnpm install
            - name: Run build
              run: pnpm run build
            - name: Install playwright browsers
              run: npx playwright install --with-deps
            - name: Run preview integration tests
              run: pnpm run test:integration
            - name: Find playwright report directory
              id: find-report-directory
              run: |
                # Search for the playwright-report directory within the monorepo
                report_directory=$(find . -type d -name "playwright-report" | head -n 1)
                echo "::set-output name=report_directory::$report_directory"
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                name: playwright-report
                path: ${{ steps.find-report-directory.outputs.report_directory }}
                retention-days: 30