name: CI/CD Pipeline
on:
    push:
        branches: [feat/playwright-cpe-int-test]
    pull_request:
        branches: [feat/playwright-cpe-int-test]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x]
        runs-on: ${{ matrix.os }}
        timeout-minutes: 15
        steps:
            - name: Checkout code repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                  run_install: true
            - name: Cache pnpm modules
              uses: actions/cache@v3
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install pnpm modules
              run: pnpm install
            - name: Run build
              run: pnpm run build
            - name: Check for changes in preview-middleware package
              if: always()
              id: check_changes
              run: |
                changed_files=$(git diff --name-only HEAD^ HEAD)
                if [[ $changed_files == *"packages/preview-middleware"* ]]; then
                  echo "::set-output name=changes::true"
                else
                  echo "::set-output name=changes::false"
                fi
            - name: Install playwright browsers
              if: always() && steps.check_changes.outputs.changes == 'true'
              run: npx playwright install --with-deps
            - name: Run integration tests
              if: always() && steps.check_changes.outputs.changes == 'true'
              run: pnpm run test:integration
            - name: Upload playwright reports
              uses: actions/upload-artifact@v3
              if: always() && steps.check_changes.outputs.changes == 'true'
              with:
                name: playwright-reports-os-${{ matrix.os }}-node-version-${{ matrix.node-version }}
                path: |
                  **/playwright-report
                  !**/node_modules
                retention-days: 15